config/routes.rb
TestApp::Application.routes.draw do
  resources :locations

  resources :individuals

  resources :financials

  resources :fundings

  resources :investments

  resources :companies

  resources :industries

end

app/models/investment.rb
class Investment < ActiveRecord::Base
  attr_accessible :funding_id, :company_peram, :company_id, :financial_perma, :financial_id, :individual_perma, :individual_id

  belongs_to :company
  belongs_to :individual
  belongs_to :financial
  belongs_to :funding


end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  # GET /investments
  # GET /investments.json
  def index
    @investments = Investment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @investments }
    end
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
    @investment = Investment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @investment }
    end
  end

  # GET /investments/new
  # GET /investments/new.json
  def new
    @investment = Investment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @investment }
    end
  end

  # GET /investments/1/edit
  def edit
    @investment = Investment.find(params[:id])
  end

  # POST /investments
  # POST /investments.json
  def create
    @investment = Investment.new(params[:investment])

    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render json: @investment, status: :created, location: @investment }
      else
        format.html { render action: "new" }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /investments/1
  # PUT /investments/1.json
  def update
    @investment = Investment.find(params[:id])

    respond_to do |format|
      if @investment.update_attributes(params[:investment])
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @investment = Investment.find(params[:id])
    @investment.destroy

    respond_to do |format|
      format.html { redirect_to investments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_form.html.erb
<%= form_for(@investment) do |f| %>
  <% if @investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
      <% @investment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :funding_id %><br />
    <%= f.number_field :funding_id %>
  </div>
  <div class="field">
    <%= f.label :investor_perma %><br />
    <%= f.text_field :investor_perma %>
  </div>
  <div class="field">
    <%= f.label :investor_id %><br />
    <%= f.number_field :investor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investments/edit.html.erb
<h1>Editing investment</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.erb
<h1>Listing investments</h1>

<table>
  <tr>
    <th>Funding ID </th>
    <th>Co. Being Funded</th>
    <th>Company perma</th>
    <th>Company Id</th>
    <th>Financial perma</th>
    <th>Financial ID</th>
    <th>Individual perma</th>
    <th>Individual ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @investments.each do |investment| %>
  <tr>
    <td><%= investment.funding_id %></td>
    <td><%= investment.funding.company.name %></td>
    <td><%= investment.company %></td>
    <td><%= investment.company_id %></td>
    <td><%= investment.financial_perma %></td>
    <td><%= investment.financial_id %></td>
    <td><%= investment.individual_perma %></td>
    <td><%= investment.individual_id %></td>
    <td><%= link_to 'Show', investment %></td>
    <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
    <td><%= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Investment', new_investment_path %>

app/views/investments/new.html.erb
<h1>New investment</h1>

<%= render 'form' %>

<%= link_to 'Back', investments_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Funding:</b>
  <%= @investment.funding_id %>
</p>

<p>
  <b>Investor perma:</b>
  <%= @investment.investor_perma %>
</p>

<p>
  <b>Investor:</b>
  <%= @investment.investor_id %>
</p>


<%= link_to 'Edit', edit_investment_path(@investment) %> |
<%= link_to 'Back', investments_path %>