config/routes.rb
TestApp::Application.routes.draw do
  resources :locations

  resources :individuals

  resources :financials

  resources :fundings

  resources :investments

  resources :companies

  resources :industries

end

app/models/individual.rb
class Individual < ActiveRecord::Base
  attr_accessible :crunch_url, :home_url, :name, :perma

  has_many :investments

end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  # GET /individuals
  # GET /individuals.json
  def index
    @individuals = Individual.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @individuals }
    end
  end

  # GET /individuals/1
  # GET /individuals/1.json
  def show
    @individual = Individual.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @individual }
    end
  end

  # GET /individuals/new
  # GET /individuals/new.json
  def new
    @individual = Individual.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @individual }
    end
  end

  # GET /individuals/1/edit
  def edit
    @individual = Individual.find(params[:id])
  end

  # POST /individuals
  # POST /individuals.json
  def create
    @individual = Individual.new(params[:individual])

    respond_to do |format|
      if @individual.save
        format.html { redirect_to @individual, notice: 'Individual was successfully created.' }
        format.json { render json: @individual, status: :created, location: @individual }
      else
        format.html { render action: "new" }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /individuals/1
  # PUT /individuals/1.json
  def update
    @individual = Individual.find(params[:id])

    respond_to do |format|
      if @individual.update_attributes(params[:individual])
        format.html { redirect_to @individual, notice: 'Individual was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individuals/1
  # DELETE /individuals/1.json
  def destroy
    @individual = Individual.find(params[:id])
    @individual.destroy

    respond_to do |format|
      format.html { redirect_to individuals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/views/individuals/_form.html.erb
<%= form_for(@individual) do |f| %>
  <% if @individual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@individual.errors.count, "error") %> prohibited this individual from being saved:</h2>

      <ul>
      <% @individual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :perma %><br />
    <%= f.text_field :perma %>
  </div>
  <div class="field">
    <%= f.label :crunch_url %><br />
    <%= f.text_field :crunch_url %>
  </div>
  <div class="field">
    <%= f.label :home_url %><br />
    <%= f.text_field :home_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/individuals/edit.html.erb
<h1>Editing individual</h1>

<%= render 'form' %>

<%= link_to 'Show', @individual %> |
<%= link_to 'Back', individuals_path %>

app/views/individuals/index.html.erb
<h1>Listing individuals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Perma</th>
    <th>Crunch url</th>
    <th>Home url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @individuals.each do |individual| %>
  <tr>
    <td><%= individual.name %></td>
    <td><%= individual.perma %></td>
    <td><%= individual.crunch_url %></td>
    <td><%= individual.home_url %></td>
    <td><%= link_to 'Show', individual %></td>
    <td><%= link_to 'Edit', edit_individual_path(individual) %></td>
    <td><%= link_to 'Destroy', individual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Individual', new_individual_path %>

app/views/individuals/new.html.erb
<h1>New individual</h1>

<%= render 'form' %>

<%= link_to 'Back', individuals_path %>

app/views/individuals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @individual.name %>
</p>

<p>
  <b>Perma:</b>
  <%= @individual.perma %>
</p>

<p>
  <b>Crunch url:</b>
  <%= @individual.crunch_url %>
</p>

<p>
  <b>Home url:</b>
  <%= @individual.home_url %>
</p>


<%= link_to 'Edit', edit_individual_path(@individual) %> |
<%= link_to 'Back', individuals_path %>